### ISSUE TITLE
Access the main page from all hosts, not just localhost

### ISSUE THREAD

**Issue by DervMan** [deckerego/GarageSecurity#17]
I wanted to access the main page from other hosts on the network but the HTTP daemon was restricted to localhost. To get around this I amended 'run_server.py' as follows. Change 'localhost' to '0.0.0.0'

`
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
from routes import application
from bottle import run

if __name__ == "__main__":
        port = int(os.environ.get("PORT", 9003))
        run(application, reloader = False, host = '0.0.0.0', port = port)
        application.close()
p
`

**Comment by deckerego** [comment]
This was done intentionally - the idea being that only Apache should be exposed to other interfaces, and Apache would be the one proxying to Bottle.
