### ISSUE TITLE
Camera0 URL on main page is a static URL

### ISSUE THREAD

**Issue by DervMan** [deckerego/GarageSecurity#18]
When accessing GarageSec main page on anything other than port 80 the camera stream is broken. This link needs to be created dynamically so TCP port changes don't break the URL.

		<script src="installed/jquery/dist/jquery.min.js"></script>
		<script src="installed/bootstrap/dist/js/bootstrap.min.js"></script>
		<script type="text/javascript" src="js/mjpeg_viewer.js"></script>
		<script type="text/javascript" src="js/events.js"></script>
		<script type="text/javascript">
			loadThermals("temperature", "humidity")
			renderCamera("camera0", "http://10.10.10.10/camera0");
			silenceStatus("silent");
			lastEvent("lastevent")
		</script>

**Comment by deckerego** [comment]
Implemented as a config change
